### ISSUE TITLE
File writes are not atomic

### ISSUE THREAD

**Issue by losfair** [RidiculousDoge/pyEncrypt#1]
The current file write implementation may cause data loss in the event of a power loss during/shortly after writes (`json.dump`). To make it safe, the new content should be written to a temporary file (on the same filesystem) first, and then [`rename(2)`](https://linux.die.net/man/2/rename) should be called to atomically replace the target file.

**Comment by RidiculousDoge** [comment]
Tks for the advice~

Experienced open-source happiness for the first time lolll
